# Generated by Django 5.1.3 on 2024-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
